// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=869bcf28d1
ROOST_METHOD_SIG_HASH=75d10f69f9


*/

// ********RoostGPT********
// Mock of the environment and prerequisites
let jest = require("jest");
let describe = jest.describe;
let beforeAll = jest.beforeAll;
let test = jest.test;
let expect = jest.expect;

// Actual test case content

const prepareData = (data) => {
  // Validate data
  if (!data || !data.main || !data.weather || data.weather.length === 0) {
    throw new Error('Invalid data format');
  }

  // Extract the necessary information
  const { name, main, weather } = data;
  const { temp } = main;
  const { speed: windSpeed } = data.wind;
  const [{ description }] = weather;

  // Return processed data
  return {
    city: name,
    temperature: temp,
    description: description,
    windSpeed: windSpeed,
  };
};

// Export the function for testing
exports.prepareData = prepareData;

// Jest test case
describe('OpenWeatherMap Data Processing', () => {
  let rawWeatherData;
  let processedData;

  beforeAll(() => {
    rawWeatherData = {
      coord: { lon: -0.1257, lat: 51.5085 },
      weather: [
        {
          id: 804,
          main: 'Clouds',
          description: 'overcast clouds',
          icon: '04d'
        }
      ],
      base: 'stations',
      main: {
        temp: 289.82,
        feels_like: 289.11,
        temp_min: 288.71,
        temp_max: 291.15,
        pressure: 1013,
        humidity: 77
      },
      visibility: 10000,
      wind: { speed: 4.12, deg: 240 },
      clouds: { all: 90 },
      dt: 1648374885,
      sys: {
        type: 2,
        id: 2019646,
        country: 'GB',
        sunrise: 1648361766,
        sunset: 1648406781
      },
      timezone: 3600,
      id: 2643743,
      name: 'London',
      cod: 200
    };

    processedData = {
      city: 'London',
      temperature: 289.82,
      description: 'overcast clouds',
      windSpeed: 4.12
    };
  });

  test('Should correctly process the raw weather data for London', () => {
    const { prepareData } = require('./weatherDataModule'); // Updated to correct path
    let result = prepareData(rawWeatherData);
    expect(result).toBeDefined();
    expect(result.city).toBe('London');
    expect(result.temperature).toBe(289.82);
    expect(result.description).toBe('overcast clouds');
    expect(result.windSpeed).toBe(4.12);
  });

  test('Should handle incorrect data format gracefully', () => {
    const { prepareData } = require('./weatherDataModule'); // Updated to correct path
    let incorrectData = { ...rawWeatherData, weather: null };
    expect(() => prepareData(incorrectData)).toThrow();
  });

  test('Should return null for missing data', () => {
    const { prepareData } = require('./weatherDataModule'); // Updated to correct path
    let incompleteData = { ...rawWeatherData, main: null };
    expect(() => prepareData(incompleteData)).toThrow();
  });
});

