// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=averagteTemp_aab1d2fafe
ROOST_METHOD_SIG_HASH=averagteTemp_ca192d32f1


*/

// ********RoostGPT********
const averageTemp = require('./prepared-for-the-weather');

describe('averageTemp function', () => {
  
  test('should correctly calculate the average of two numbers', () => {
    const result = averageTemp(10, 20);
    expect(result).toBe(15);
  });

  test('should return the input value if both min and max are the same', () => {
    const result = averageTemp(25, 25);
    expect(result).toBe(25);
  });

  test('should calculate average correctly for negative temperatures', () => {
    const result = averageTemp(-10, -20);
    expect(result).toBe(-15);
  });

  test('should handle non-numeric inputs by throwing an error', () => {
    expect(() => averageTemp('a', 10)).toThrow(Error);
    expect(() => averageTemp(10, 'b')).toThrow(Error);
    expect(() => averageTemp('a', 'b')).toThrow(Error);
  });

  test('should handle case when inputs are not provided by throwing an error', () => {
    expect(() => averageTemp()).toThrow(Error);
  });
});

