// ********RoostGPT********
/*
Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview

ROOST_METHOD_HASH=kelvinToCelcius_c4e254281d
ROOST_METHOD_SIG_HASH=kelvinToCelcius_5ac945d542


*/

// ********RoostGPT********
const kelvinToCelcius = (kTemp) => {
  if (typeof kTemp !== 'number') {
    throw new Error('Temperature must be a number');
  }
  if (kTemp < 0) {
    throw new Error('Invalid temperature: Kelvin cannot be negative');
  }
  return kTemp - 273;
};

module.exports = { kelvinToCelcius };

